# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - release
  - docker
  
variables:
  CARGO_HOME: '.cargo'

build:
  stage: build
  except:
    - master
  cache:
    key: debug
    paths:
      - target/
      - $CARGO_HOME
  artifacts:
    paths:
      - target/debug/samotop
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build
    
build-release:
  extends: build
  only:
    - master
  cache:
    key: release
    paths:
      - target/
      - $CARGO_HOME
  artifacts:
    paths:
      - target/release/samotop
      - Cargo.lock
  script:
    - cargo build --release

test-stable:
  stage: test
  except:
    - master
  cache:
    key: debug
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  script:
    - cargo test --all

test-nightly:
  extends: test-stable
  before_script:
    - rustup default nightly

publish-lib:
  stage: release
  only:
    - master
  cache:
    key: release
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  script:
    - cargo test --all --release
    - cargo publish --token "$CRATES_KEY"

build-server:
  stage: docker
  except:
    - master
  image: "docker:git"
  services:
    - docker:dind
  script:
    - cp target/debug/samotop docker/
    - cd docker/
    - docker build -t samotop .
    - docker run -t --rm samotop | tee docker.log

publish-server:
  extends: build-server
  only:
    - master
  script:
    - cp target/release/samotop docker/
    - cd docker/
    - docker build -t samotop .
    - docker run -t --rm samotop | tee docker.log
    - tag="brightopen/samotop:$(cat docker.log | cut -d ' ' -f2 | tr -d \\n\\r)"
    - echo "$tag"
    - docker tag samotop "$tag"
    - docker login -u "$DOCKER_USR" -p "$DOCKER_PWD"
    - docker push "$tag"
