# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/rust/tags/
image: "rust:latest"

stages:
  - build
  - test
  - release
  
variables:
  CARGO_HOME: '.cargo'

build-debug:
  stage: build
  before_script:
    - rustc --version
    - cargo --version
  script:
    - cargo build --features tls
  cache:
    key: debug
    paths:
      - target/
      - $CARGO_HOME
  except:
    - tags

build-nightly:
  extends: build-debug
  before_script:
    - rustup default nightly
  cache:
    policy: pull
    key: debug
    paths:
      - target/
      - $CARGO_HOME

build-release:
  stage: build
  script:
    - cargo build --features tls --release
  cache:
    paths:
      - target/
      - $CARGO_HOME
  artifacts:
    paths:
      - target/release/samotop
      - Cargo.lock
  only:
    - master
  except:
    - tags
    
test-tls:
  stage: test
  script:
    - cargo test --all --features tls
  cache:
    key: debug
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  except:
    - tags

test-notls:
  stage: test
  script:
    - cargo test --all
  cache:
    key: debug
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  except:
    - tags

publish-lib:
  stage: release
  only:
    - master
  except:
    - schedules
  script:
    - cargo publish --token "$CRATES_KEY"
  cache:
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  except:
    - tags

publish-server:
  stage: release
  only:
    - master
  except:
    - schedules
  script:
    - docker login -u "$DOCKER_USR" -p "$DOCKER_PWD" https://docker.io
    - cargo build --features tls --release
    - docker build -t samotop .
    - export tag="docker.io/brightopen/samotop:$(docker run -t --rm samotop samotop -V | cut -d ' ' -f2)"
    - docker tag "$tag" samotop
    - docker push "$tag"
  cache:
    policy: pull
    paths:
      - target/
      - $CARGO_HOME
  except:
    - tags
